osism/release

- latest/base.yml
> latest: use ansible >= 4.0.0 for osism-ansible

- latest/base.yml
This reverts commit 3c4b64a94d9f979a726c443a60e61e4ee723a92f.
> Revert "latest: use ansible >= 4.0.0 for osism-ansible"

- notes/3.0.0/NOTES.md
There are security concerns about Tailscale.
Accordingly, it is removed again.
> notes: remove tailscale

- etc/images.yml
Parameter is left and is no longer needed.
> Remove keycloak_for_traefik

- latest/base.yml
- src/update-base-versions.py
Necessary to be able to work with the DB_ parameters
> latest: use keycloak 17.0.0-legacy

- 3.0.0/base.yml
Fix indentation in the Homer config template
> 3.0.0: use osism.services v0.9.0

- .github/renovate.json
- Fix the in the title called bug with adding a regexp to the renovate.json
- This closes issue#352
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
> Fix the Renovate-Docker-Version-Bug with the v what not should be shown

- 3.2.0/base.yml
Because of the wrong ironic_inspector_tag.
> 3.2.0: update defaults for base

- latest/ceph-pacific.yml
Should be Ansible 2.10.x and not Ansible 2.9.x
Closes osism/issues#293
> latest: fix ansible version for ceph-pacific

- notes/4.0.0/NOTES.md
Related to osism/ansible-collection-services#822
> 4.0.0: deprecated hddtemp

- notes/4.0.0/NOTES.md
> 4.0.0: deprecate the old docker-compose CLI

- doc/source/notes/5.0.0.rst
> notes: ansible is now an extra requirements in python-osism

- latest/base.yml
Upstream no longer builds the tag since version 3.2.5.
Part of osism/issues#376
> netbox: use tag without -ldap

- doc/source/notes/5.0.0.rst
- latest/base.yml
Support for Zabbix was already removed in OSISM 3.0.0. The Ansible collection community.zabbix was still present as a leftover.
> latest: remove community.zabbix ansible collection

- doc/source/index.rst
The release submodule was remved from osism/container-images/kolla.
> docs: the release submodule most not be updated

- 4.2.0/base.yml
Required to use everywhere the same version.
> 4.2.0: use osism 0.7.0

- doc/source/notes/4.2.0.rst
> 4.2.0: add external_ceph_always_copy_cinder_keyring

- doc/source/notes/5.0.0.rst
https://review.opendev.org/c/openstack/governance/+/866562
OVH takes over. Gates are green again.
> notes: do not remove mistral

- latest/openstack-xena.yml
- latest/openstack-yoga.yml
- latest/openstack-zed.yml
Required to be able to still build older versions.
Related to d42e65e7b8d3f3e9b219e6261903eaa004f637c5
> latest/openstack: re-add ansible_version

- doc/source/notes/5.0.0.rst
Because of https://github.com/vexxhost/magnum-cluster-api the Magnum service makes now sense in the contect of the SCS project.
> notes: do not deprecate magnum

- latest/openstack-zed.yml
There are far fewer OpenStack releases being made today than in the past. A large part of the backports and fixes now only end up on stable branches and are no longer released with their own tag. Therefore, we are switching to the stable branches starting with Zed.
> zed: use stable branches

- latest/openstack-zed.yml
This way we're able to already build ovs images with our own openvswitch packages.
> zed: remove ovsdpdk for the moment

- latest/openstack-zed.yml
Since we now want to work with Open vSwitch 3.1.0, we would first have to disable DPDK again.
> zed: remove ovsdpdk for the moment (again)

- latest/base.yml
> Fix tag for pdns_recursor ansible role

- 5.1.0/openstack-zed.yml
Not possible with the new OVS 3.1 packages at the moment.
> 5.1.0: do not build ovsdpdk images

- etc/images.yml
Information from zuul-announce@lists.zuul-ci.org from 2023-04-27 22:14 CEST
depends: osism/ansible-defaults#123
Signed-off-by: Tim Beermann <beermann@osism.tech>
> Registries: Change zuul registry to quay.io. Unfortunately the org name changed.

- 4.3.0/base.yml
Required to make all new patches in osism/container-image-osism-ansible usable.
> 4.3.0: update hardening role

- latest/base.yml
This reverts commit 0506907526ead43b33756b52769165b4ba028687.
v20.10.25 is still not available as a package.
> Revert "chore(deps): update dependency moby/moby to v20.10.25"

- latest/base.yml
We do not use Zuul in deployments. It is an external service. Therefore, the version of Zuul used does not need to be listed in osism/release. The version used is independent of a release.
> latest: remove zuul versions

- doc/source/index.rst
Only the releases atom feed is relevant for final releases.
> docs: remove the tags atom feed

- doc/source/notes/7.0.0a.rst
This reverts commit 2690b5e398f881012457e42c18b39c69384b8572.
> Revert "7.0.0a: use RabbitMQ quorum queues (#1213)"

- latest/openstack-2023.2.yml
- latest/openstack-2024.1.yml
Only the versions that can also use the latest Ansible core.
> latest: use renovate to update openstack ansible-core version

- doc/source/index.rst
- doc/source/notes/7.rst
> doc: add 7.0.2 release notes

- latest/ceph-quincy.yml
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.
> latest: back to ansible 2.15 for ceph quincy

- latest/base.yml
They are now part of osism-kubernetes.
> latest: remove helm_chart_repositories

- .github/renovate.json
- 2.18.4 -> 2.18.5: OK
- 2.17.2 -> 2.17.3: OK
- 2.17.2 -> 2.18.5: NOT OK
> renovate: restrict Ansible updates to patch versions only
