osism/release

etc/roles-manager.yml
etc/roles.yml
latest/base.yml

Cleanup osism roles

---

latest/openstack-latest.yml

latest: add logstash image & use ELK 7.x

---

latest/openstack-latest.yml

latest: disable skydive for the moment

---

latest/openstack-latest.yml
latest/openstack-rocky.yml
latest/openstack-stein.yml
latest/openstack-train.yml
latest/openstack-ussuri.yml
latest/openstack-victoria.yml

latest: remove ovsdpdk image

---

latest/base.yml

latest: update hardening role

---

latest/ceph-pacific.yml

latest: add ceph pacific

---

latest/base.yml

latest: use awxclient 19.0.0

---

latest/openstack-master.yml

latest: add openstack-master.yml symlink

---

latest/ceph-pacific.yml

latest: fix typo

---

latest/openstack-latest.yml
latest/openstack-victoria.yml

openstack: add senlin service

---

latest/openstack-victoria.yml

latest: enable logstash for victoria

---

latest/openstack-latest.yml
latest/openstack-victoria.yml

latest: add storm service

---

latest/openstack-latest.yml
latest/openstack-victoria.yml

latest: add trove service

---

etc/roles.yml
latest/base.yml

Add stackhpc.systemd_networkd role

---

etc/roles.yml
latest/base.yml

Add libvirt roles

---

.github/workflows/update-base-versions.yml
.github/workflows/update-openstack-versions.yml

github: add workflow_dispatch to update workflows

---

.github/workflows/update-openstack-versions.yml

github: add version to branch name/commit title

---

etc/roles.yml

Fix stackhpc git urls

---

etc/images.yml

Add osism/inventory-reconciler image

---

latest/openstack-wallaby.yml

Add openstack wallaby release

---

latest/base.yml

latest/base: add ansible_base version

---

etc/roles-manager.yml
etc/roles.yml
latest/base.yml

latest: remove ANXS.apt ansible role

---

latest/openstack-latest.yml
latest/openstack-victoria.yml
latest/openstack-wallaby.yml

latest: re-enable cloudkitty images

---

src/update-base-versions.py

Closes #90.
Signed-off-by: Tim Beermann <beermann@betacloud-solutions.de>

Fixed postgres version calculation

---

src/update-base-versions.py

Do not rely on docker hub for the postgres version

---

etc/roles.yml
latest/base.yml

Add ansible role "geerlingguy.certbot"

---

.github/workflows/update-base-versions.yml
.github/workflows/update-openstack-versions.yml

github: improve update workflows

---

.github/workflows/update-openstack-versions.yml
src/update-openstack-versions.py

github: update all openstack versions in one go

---

etc/collections.yml
latest/base.yml

Add ansible collections

---

latest/base.yml

Add missing awx.awx version

---

etc/collections.yml
latest/base.yml

Fix ansible collections

---

etc/collections.yml
latest/base.yml

Fix version of the netcommon collection

---

latest/base.yml

Use main branch for arista.eos collection

---

etc/collections.yml
latest/base.yml

Use arista.eos from galaxy

---

latest/base.yml

Use main branch for osism.validations collection

---

latest/ceph-luminous.yml
latest/ceph-nautilus.yml

latest: remove old ceph versions

---

latest/base.yml
latest/ceph-latest.yml
latest/ceph-octopus.yml
latest/ceph-pacific.yml
latest/openstack-latest.yml
latest/openstack-victoria.yml
latest/openstack-wallaby.yml

latest: add generics version

---

latest/base.yml
latest/ceph-latest.yml
latest/ceph-octopus.yml
latest/ceph-pacific.yml
latest/openstack-latest.yml
latest/openstack-victoria.yml
latest/openstack-wallaby.yml

latest: add defaults version

---

latest/base.yml
latest/ceph-latest.yml
latest/ceph-octopus.yml
latest/openstack-latest.yml
latest/openstack-victoria.yml
latest/openstack-wallaby.yml

latest: add playbooks version

---

.flake8
1.0.0/base.yml
1.0.0/ceph.yml
1.0.0/openstack.yml
README.md
etc/other.yml
latest/base.yml
requirements.txt
src/prepare-release.py
src/update-base-versions.py
src/update-openstack-versions.py

Release 1.0.0 preparations

---

1.0.0/ceph-pacific.yml
1.0.0/openstack-wallaby.yml

1.0.0: set openstackclient, cephclient + ceph-daemon versions

---

1.0.0/base.yml
latest/base.yml
src/prepare-release.py

Remove repository_version

---

1.0.0/base.yml
1.0.0/ceph-pacific.yml
1.0.0/openstack-wallaby.yml

1.0.0: update versions

---

README.md

README: add list of container images with release specific tags

---

1.0.0/base.yml
1.0.0/ceph-pacific.yml
1.0.0/openstack-wallaby.yml

1.0.0: fix defaults version

---

etc/images.yml
latest/base.yml

latest: add keycloak image

---

latest/ceph.yml
latest/openstack.yml

latest: add openstack.yml & ceph.yml symlinks

---

latest/base.yml

latest: sed redis version

---

latest/base.yml

latest: use netbox ldap image

---

latest/base.yml

latest: use netbox v3.0.2-ldap

---

latest/base.yml

latest: add operations_version

---

.github/workflows/update-base-versions.yml
.github/workflows/update-openstack-versions.yml

github: fix update workflows

---

src/update-base-versions.py

Use netbox ldap image

---

.github/workflows/update-versions.yml

github: install missing pyyaml package

---

.github/workflows/update-versions.yml
src/update-base-versions.py

Improve update-base-versions.py script

---

latest/base.yml
src/update-base-versions.py

latest: update keycloak version

---

README.md

README: add Ansible collections with release specific tags

---

2.0.0/base.yml
2.0.0/ceph-pacific.yml
2.0.0/ceph.yml
2.0.0/openstack-wallaby.yml
2.0.0/openstack.yml
etc/other.yml
src/prepare-release.py

Release 2.0.0 preparations

---

2.0.0/ceph-pacific.yml
2.0.0/openstack-wallaby.yml

2.0.0: fix openstackclient, cephclient & ceph-daemon versions

---

src/update-base-versions.py

Improve update-base-versions.py

---

latest/base.yml

latest/base: pin ansible versions

---

latest/base.yml

latest/base: fix ansible-base version

---

latest/base.yml

latest: remove ansible-base

---

notes/3.0.0/NOTES.md

releasenotes: remove zabbix

---

etc/images.yml
latest/base.yml

latest: use awx 19.4.0

---

etc/images.yml

Use our own netbox image

---

etc/images.yml

Add scheduler image

---

notes/3.0.0/NOTES.md

notes: add netbox + celery

---

notes/3.0.0/NOTES.md

notes: add new stuff

---

notes/3.0.0/NOTES.md

notes: deprecate the generic-configuration playbook

---

etc/images.yml
latest/base.yml

Add vault image

---

etc/images.yml
latest/base.yml

Add alerta image

---

notes/3.0.0/NOTES.md

notes: add grafana dashboards

---

notes/3.0.0/NOTES.md

notes: add docker-compose cli plugin

---

notes/3.0.0/NOTES.md

notes: mention testbed minification

---

notes/3.0.0/NOTES.md

notes: add Nexus OSS service

---

notes/3.0.0/NOTES.md

notes: add tang service

---

notes/3.0.0/NOTES.md

notes: add virtualbmc service

---

notes/3.0.0/NOTES.md

notes: add container-images repository

---

notes/3.0.0/NOTES.md

notes: add fluendt watch timer

---

etc/images.yml
notes/3.0.0/NOTES.md

Use our own nexus image

---

notes/3.0.0/NOTES.md

notes: add missing features

---

notes/3.0.0/NOTES.md

notes: mention cadvisor performance fix

---

notes/3.0.0/NOTES.md

notes: enable neutron port forwarding extension by default

---

latest/openstack-victoria.yml
latest/openstack-wallaby.yml

latest: re-add zun

---

etc/images.yml
latest/base.yml

Add traefik image

---

latest/base.yml

latest: use netbox v3.1.0-ldap

---

latest/base.yml

latest: use nexus 3.37.0

---

notes/3.0.0/NOTES.md

notes: add log4j

---

notes/3.0.0/NOTES.md

notes: rolling upgrades of Glance enabled by default

---

latest/openstack-xena.yml

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

Add openstack xena release

---

latest/ceph-nautilus.yml

latest: add ceph nautilus

---

notes/3.0.0/NOTES.md

partly: osism/issues#65
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

change docker-compose to docker compose v2

---

notes/3.0.0/NOTES.md

notes: add traefik & nexus automation

---

notes/3.0.0/NOTES.md

notes: add overlord service

---

notes/3.0.0/NOTES.md

notes: add new harbor service

---

etc/images.yml
latest/base.yml

latest: add atlantis image

---

notes/3.0.0/NOTES.md

notes: add clamav

---

notes/3.0.0/NOTES.md

notes: add dnsdist service

---

etc/images.yml
latest/base.yml

Add dnsdist image

---

latest/base.yml

latest: update ansible network modules

---

latest/base.yml

latest: use ansible 5.2.0

---

latest/base.yml
src/update-base-versions.py

latest: update the traefik version

---

latest/base.yml
src/update-base-versions.py

latest: update the vault version

---

latest/base.yml
src/update-base-versions.py

latest: update the boundary version

---

etc/images.yml
latest/base.yml

latest: add zuul images

---

etc/images.yml

Use our own keycloak image

---

etc/images.yml
latest/base.yml

Add cgit image

---

notes/3.0.0/NOTES.md

notes: add cgit service

---

notes/3.0.0/NOTES.md

notes: add deprecations & frrouting service

---

notes/3.0.0/NOTES.md

notes: remove awx technical preview

---

latest/base.yml
src/update-base-versions.py

latest: remove awx

---

notes/3.0.0/NOTES.md

notes: deprecated the haproxy inventory group

---

etc/collections.yml
etc/images.yml

Remove some more AWX leftovers

---

latest/base.yml

latest: use netbox 3.1.8

---

notes/3.0.0/NOTES.md

notes: add openstack xena release

---

notes/3.0.0/NOTES.md

notes: add homer to the list of traefik integrations

---

etc/openstack.yml
latest/openstack-latest.yml
latest/openstack-xena.yml
notes/3.0.0/NOTES.md

Remove panko

---

etc/collections.yml

Use more collections from the ansible galaxy

---

latest/openstack.yml

latest: openstack.yml -> openstack-xena.yml

---

notes/3.0.0/NOTES.md

Signed-off-by: Felix Kronlage-Dammers <fkr@hazardous.org>

It is Netbox, not Nexbox

---

notes/3.0.0/NOTES.md

Signed-off-by: Felix Kronlage-Dammers <fkr@hazardous.org>

Removed images should be among the removals

---

3.0.0/base.yml

3.0.0: sync defaults to fix a double pipe

---

etc/images.yml

Add missing osism-netbox image

---

.github/renovate.json

renovate: group zuul dependencies

---

notes/4.0.0/NOTES.md

Close https://github.com/osism/release/issues/404#event-6659995549
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

Wireguard: Add wireguard to the release notes

---

.zuul.yaml
tox.ini

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

Initial zuul tox linters job

---

3.2.0/openstack-xena.yml

Because of the wrong ironic_inspector_tag.

3.2.0: update defaults for kolla/openstack

---

3.2.0/base.yml
3.2.0/ceph-pacific.yml
3.2.0/openstack-xena.yml
latest/base.yml
latest/ceph-latest.yml
latest/ceph-octopus.yml
latest/ceph-pacific.yml
latest/openstack-wallaby.yml
latest/openstack-xena.yml

Add missing playbooks_version & improve syntax

---

3.2.0/base.yml

3.2.0: use inventory reconciler 3.2.0

---

etc/images.yml
latest/base.yml

partly osism/issues#217
Signed-off-by: Tim Beermann <beermann@osism.tech>

add squid image

---

notes/4.0.0/NOTES.md

partly osism/issues#217
Signed-off-by: Tim Beermann <beermann@osism.tech>

notes: add squid service

---

latest/openstack-yoga.yml

latest: add openstack yoga

---

latest/openstack-yoga.yml

latest: fix yoga kuryr version

---

latest/openstack-wallaby.yml
latest/openstack-xena.yml
latest/openstack-yoga.yml

latest: add openstack_previous_version

---

source/index.rst

Signed-off-by: Felix Kronlage-Dammers <fkr@hazardous.org>

'As of' not 'A of'

---

notes/4.0.0/NOTES.md

4.0.0: add elasticsearch curator

---

notes/4.0.0/NOTES.md

* yaml lint
* ansible v6
* ubuntu 22.04
* openstack yoga

notes: add missing details for 4.0.0

---

notes/4.0.0/NOTES.md

4.0.0: remove scan_services plugin

---

notes/4.0.0/NOTES.md

notes: add ansible roles documentation

---

notes/4.0.0/NOTES.md

notes: add links to yoga release notes

---

notes/4.0.0/NOTES.md

notes: add sbom checksums

---

notes/4.0.0/NOTES.md

Signed-off-by: Felix Kronlage-Dammers <fkr@hazardous.org>

fix wording

---

latest/ceph-quincy.yml

latest: prepare ceph-quincy

---

notes/4.0.0/NOTES.md

4.0.0: add ceph quincy

---

4.0.0a/base.yml
4.0.0a/ceph-pacific.yml
4.0.0a/ceph.yml
4.0.0a/openstack-yoga.yml
4.0.0a/openstack.yml
notes/4.0.0a/NOTES.md
source/index.rst
src/prepare-release.py

Prepare 4.0.0a release

---

doc/source/index.rst

doc: sync the reconciler & refresh facts

---

notes/4.0.0/NOTES.md

notes: add link to the ceph pacific release notes

---

notes/4.0.0/NOTES.md

4.0.0: add docker_registry* parameters

---

4.0.0b/base.yml
4.0.0b/ceph-pacific.yml
4.0.0b/ceph.yml
4.0.0b/openstack-yoga.yml
4.0.0b/openstack.yml
doc/source/index.rst

Prepare 4.0.0b release

---

doc/source/index.rst

doc: how do you do a stable relesae

---

doc/source/index.rst

doc: generate openstack image checksums

---

4.0.0b/base.yml

4.0.0b: fix ansible-defaults version

---

doc/source/index.rst

doc: also tage the cfg-cookiecutter repository

---

4.0.0/base.yml
4.0.0/ceph-pacific.yml
4.0.0/ceph.yml
4.0.0/openstack-yoga.yml
4.0.0/openstack.yml
doc/source/index.rst

Prepare 4.0.0 release

---

4.0.0/ceph-pacific.yml
4.0.0/openstack-yoga.yml

4.0.0: bump defaults for ceph + openstack as well

---

doc/source/conf.py
doc/source/index.rst
doc/source/notes/4.0.0.rst

The notes directory remains, but will no longer
be used in the future.

doc: add 4.0.0 notes

---

doc/source/index.rst
doc/source/notes/5.0.0.rst

notes: openstack-image-manager @ pypi

---

doc/source/notes/5.0.0.rst

notes: add openstack-image-manager container image

---

doc/source/notes/5.0.0.rst

notes: add mitogen plugin

---

doc/source/notes/5.0.0.rst

notes: add openstack zed release notes

---

latest/openstack.yml

latest: update openstack symlink to yoga

---

doc/source/conf.py
doc/source/notes/4.0.0.rst
doc/source/notes/5.0.0.rst
requirements.txt

doc: use sphinx material theme

---

doc/source/notes/5.0.0.rst

notes: add version-specific image metadata

---

doc/source/notes/5.0.0.rst
latest/openstack-xena.yml
latest/openstack-yoga.yml

latest: remove storm + zookeeper images

---

doc/source/notes/5.0.0.rst
latest/openstack-xena.yml
latest/openstack-yoga.yml

latest: remove kafka image

---

doc/source/notes/5.0.0.rst

notes: remove routeros plugin

---

doc/source/notes/5.0.0.rst

notes: add node-image

---

doc/source/notes/5.0.0.rst
latest/base.yml

notes: remove arista + juniper ansible collections

---

doc/source/notes/5.0.0.rst

notes: netbox-plugin-osism @ pypi

---

.flake8
src/images.py
src/prepare-release.py

Autoformat python syntax with black

---

doc/source/notes/5.0.0.rst

notes: deprecate bird

---

doc/source/notes/5.0.0.rst

notes: add ceph purge playbooks

---

doc/source/notes/5.0.0.rst

notes: move netbox-plugin-osism

---

doc/source/notes/5.0.0.rst
etc/collections.yml
latest/base.yml

Add osism.sonic

---

doc/source/notes/5.0.0.rst
etc/collections.yml

Move ansible-collection-sonic to osism-sonic org

---

doc/source/notes/5.0.0.rst

notes: add oim image updates

---

doc/source/notes/5.0.0.rst

notes: add new openstack-image-manager features

---

doc/source/notes/5.0.0.rst

openstack: deprecate some openstack services

---

doc/source/notes/5.0.0.rst

notes[oim]: add --check and SCS standard

---

doc/source/notes/5.0.0.rst

notes: merge dup deprecation sections

---

doc/source/notes/5.0.0.rst

notes: add enable_auditd

---

doc/source/notes/5.0.0.rst

notes: deprecate minikube

---

etc/images.yml
latest/base.yml

Add fleetdm/fleet container image

---

doc/source/notes/5.0.0.rst

notes: remove declaration of the compose version

---

doc/source/notes/5.0.0.rst

notes: add osquery service

---

latest/openstack-zed.yml

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

Add openstack zed

---

latest/openstack-zed.yml

latest/zed: use opensearch instead of elasticsearch/kibana

---

doc/source/notes/5.0.0.rst

notes: add dump facts command

---

doc/source/notes/5.0.0.rst

notes: add log ansible command

---

doc/source/notes/5.0.0.rst

notes: add log container command

---

doc/source/notes/5.0.0.rst

notes: add validate command

---

doc/source/notes/5.0.0.rst

notes: mention ara 1.6.x in the upgrade notes

---

doc/source/notes/5.0.0.rst
latest/base.yml

Required by https://github.com/techno-tim/k3s-ansible

latest: add ansible.utils & kubernetes.core collections

---

doc/source/notes/5.0.0.rst

notes: deprecate skydive

---

doc/source/notes/5.0.0.rst

notes: add console shortcuts

---

doc/source/notes/5.0.0.rst

notes: add container prompt

---

doc/source/notes/5.0.0.rst

notes: collect facts every 12 hours

---

doc/source/notes/5.0.0.rst

notes: add osism validate ceph-config

---

doc/source/notes/5.0.0.rst

notes: add missing console container prompt shortcut

---

doc/source/notes/5.0.0.rst

notes: add osism manage images

---

latest/openstack-xena.yml

latest: update openstack xena versions

---

doc/source/notes/5.0.0.rst

notes: remove docker-compose CLI

---

doc/source/index.rst

docs: use 4.2.0 in the samples

---

doc/source/notes/5.0.0.rst

notes: add osism console clush

---

latest/base.yml

latest: add ansible-core version to base.yml

---

doc/source/notes/4.2.0.rst

notes/4.2.0: mention osism/issues#421

---

doc/source/notes/5.0.0.rst

notes: add validate ceph-* commands

---

latest/openstack-zed.yml

latest: add skyline to zed

---

latest/openstack-xena.yml
latest/openstack-yoga.yml
latest/openstack-zed.yml

latest: update versions

---

latest/openstack-zed.yml

latest: fix skyline repositories

---

latest/openstack-xena.yml
latest/openstack-yoga.yml
latest/openstack-zed.yml

latest/openstack: use ansible-core

---

doc/source/notes/5.0.0.rst

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

Add notes about upgrading to OpenStack Zed

---

doc/source/notes/5.0.0.rst

notes: add osism.commons.docker_login role

---

doc/source/index.rst

doc: mention use of tags

---

doc/source/notes/5.0.0.rst

notes: mention ansible-core

---

latest/openstack-zed.yml

latest: use ansible 2.13 for openstack zed

---

doc/source/index.rst

doc: how to update the stable version in osism/testbed

---

doc/source/notes/5.0.0.rst

notes: add ironic_dnsmasq_dhcp_ranges to upgrade notes

---

doc/source/notes/5.0.0.rst

notes: add new rabbitmq + mariadb datadir volumes

---

5.0.0a/base.yml
5.0.0a/ceph-pacific.yml
5.0.0a/ceph.yml
5.0.0a/openstack-zed.yml
5.0.0a/openstack.yml
doc/source/notes/5.0.0.rst

Prepare pre-release 5.0.0a

---

.github/renovate.json
latest/base.yml

Update ansible-core version with renovate

---

doc/source/notes/5.0.0.rst

notes: mention ansible 2.14 is not usable with mitogen

---

doc/source/notes/5.0.0.rst

notes: mention use of ansible 6.7.0 @ ubuntu 20.04

---

doc/source/notes/5.0.0.rst

notes: add more testbed information

---

latest/openstack-zed.yml

This reverts commit 3f7a986d140606e0d166c5abd9c56aa4ac83a2a7.

Revert "zed: remove ovsdpdk for the moment"

---

etc/roles.yml
latest/base.yml

Source is https://github.com/PowerDNS/pdns_recursor-ansible

Add pdns_recursor ansible role

---

doc/source/notes/5.0.0.rst

5.0.0: mention netplan in upgrade nodes

---

etc/images.yml
latest/base.yml

latest: add postgres_upgrade image

---

doc/source/notes/6.0.0.rst

Add aptly as a new feature.
relates SovereignCloudStack/issues#338
Signed-off-by: Tim Beermann <beermann@osism.tech>

Add aptly as a new feature.

---

latest/openstack-2023.1.yml
latest/openstack-yoga.yml
latest/openstack-zed.yml

We do not use this image anywhere.

openstack/latest: disable collectd image

---

latest/openstack-2023.1.yml
latest/openstack-yoga.yml
latest/openstack-zed.yml

* chrony:
* etcd
* influxdb
* logstash

openstack/latest: disable some more images

---

latest/base.yml

Related to e9cbbaf71e201053babe01b4f82b0adb2b34646a.

latest: remove zookeeper version

---

latest/openstack-2023.1.yml

latest: use gnocchi stable/4.6

---

6.0.0b/base.yml
6.0.0b/ceph-quincy.yml
6.0.0b/ceph.yml
6.0.0b/openstack-2023.1.yml
6.0.0b/openstack.yml
doc/source/index.rst

Hide 6.0.0 release notes for the moment to avoid confusions when writting them.

Prepare version 6.0.0b

---

doc/source/notes/6.0.0.rst

6.0.0: add neutron/octavia issue

---

latest/openstack-2023.1.yml

This reverts commit 97fc2314a7f6b75d5472268f5c7d991a80b89b57.

Revert "latest: use ansible 2.15 for openstack 2023.1"

---

doc/source/notes/7.0.0b.rst

* octavia_persistence_database_password secret
* new location of the haproxy.pem file

7.0.0b: add more notes

---

doc/source/notes/7.0.0b.rst

7.0.0b: add "create potentially missing keys (rbd and rbd-mirror)" issue

---

doc/source/notes/7.0.0b.rst

7.0.0b: mention new diretory names in the fluentd container image

---

7.0.0c/base.yml
latest/base.yml

This is a dependency for https://github.com/osism/issues/issues/880

Add rook-release helm chart

---

doc/source/notes/7.0.0d.rst

7.0.0d: do not enable jobboard by default

---

7.0.0/base.yml
7.0.0/ceph-quincy.yml
7.0.0/openstack-2023.2.yml

Include the infrastructure/kubernetes-monitoring play.

7.0.0: use playbooks 0.20240319.1

---

doc/source/notes/7.rst

Related to 8ce4ad0c11baf289676eb8cd92ff18e9bbd98057

docs: add missing file

---

doc/source/index.rst
doc/source/notes/6.0.0.rst
doc/source/notes/7.0.0b.rst
doc/source/notes/7.0.0c.rst

Part of https://github.com/osism/issues/issues/927

Replace osism.github.io with osism.tech

---

doc/source/index.rst
doc/source/notes/7.rst

doc: add 7.0.1 release notes

---

latest/openstack-2023.2.yml
latest/openstack-2024.1.yml

latest: enable zun builds for 2023.2 & 2024.1

---

latest/openstack-2023.2.yml
latest/openstack-2024.1.yml

Build kuryr container

---

doc/source/index.rst
doc/source/notes/7.rst

doc: add 7.0.3 release notes

---

doc/source/notes/7.rst

Mention octavia valid interfaces in the release notes

---

etc/images.yml
latest/base.yml

closes https://github.com/osism/issues/issues/1037

Add rook images (#1037)

---

etc/images.yml
latest/base.yml

latest: remove openstack-healh-monitor image

---

8.0.0-rc.2/base.yml
8.0.0-rc.2/ceph-quincy.yml
8.0.0-rc.2/ceph.yml
8.0.0-rc.2/openstack-2024.1.yml
8.0.0-rc.2/openstack.yml

Add 8.0.0-rc.2

---

latest/base.yml

* pdns_recursor
* proxmox
* ubuntu22_cis

latest: manage some more role versions with renovate

---

latest/base.yml

latest: add purestorage.flasharray ansible collection

---

latest/openstack-2023.1.yml
latest/openstack-2023.2.yml
latest/openstack-2024.1.yml
latest/openstack-2024.2.yml

Disable heat, kuryr & zun builds.

latest: cleanup openstack images

---

latest/base.yml

Related to 35dbafe948956ec203ed5883ff301909bd8e5a2b

latest: fix renovate line for dnsmasq image

---

latest/base.yml

The ansible collection is now part of osism-kubernetes.

latest: remove kubernetes.core ansible collection

---

etc/images.yml
latest/base.yml

Roo is now part of osism-kubernetes.

latest: remove rook

---

latest/ceph-quincy.yml

Related to 280c417e3ccc82ddba6dbcc08c42aab3fb60c34d

latest: fix cephclient version

---

src/create-version.py

Add ceph-ansible version detection to create-version script

---

latest/openstack-2024.2.yml

latest: re-enable heat in 2024.2

---

etc/images.yml
latest/base.yml

latest: add substation image
